name: Calling workflow to provide a secret
on: 
  workflow_dispatch:

jobs:
  some-job:
    outputs:
      secrets: ${{ steps.generate-matrix-input.outputs.additionals }}
    runs-on: ubuntu-latest
    environment: PRO
    steps:
      - name: Checkout (required for gh)
        uses: actions/checkout@v6

      - name: Generate overview of secrets
        id: generate-matrix-input
        uses: ./pass-through
        with:
          additionals: ${{ secrets.MYSECRET }}
          
  call-workflow-passing-data:
    needs: some-job
    uses: kevinvissers/workflow-tricks/.github/workflows/reusable-wf.yml@master
    with:
      additionals: ${{ needs.some-job.outputs.secrets }}
