name: Fetch secrets dynamically

on:
  workflow_dispatch:

jobs:
  get-available-secrets:
    runs-on: ubuntu-latest
    environment: PRO
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      count:  ${{ steps.set-matrix.outputs.count }}
    steps:
      - name: Checkout (required for gh)
        uses: actions/checkout@v6

      - name: Store secret overview in file
        env:
          GH_TOKEN: ${{ secrets.PAT }} 
        run: |
          gh secret list --env PRO --json name >> secrets.json
          cat secrets.json

      - uses: actions/github-script@v8
        id: set-matrix
        with:
          script: |
            const fs = require('fs');
            
            let matrix = '{"include":[';

            const data = fs.readFileSync('secrets.json', 'utf8');
            console.log(data);
            
            json = JSON.parse(data);
            console.log(json);
            
            json.forEach(function(obj) {
                console.log(obj.name);
                matrix += `{"secret":"${obj.name}"},`
            });
            
            matrix += "]}";

            console.log(matrix);
            console.log(json.length);
            
            core.setOutput("matrix", matrix);
            core.setOutput('count', json.length);
  
  upload-secret-as-artifact:
    needs: get-available-secrets
    runs-on: ubuntu-latest
    environment: PRO # needs access to the environment to be able to fetch the secret
    strategy:
      matrix: ${{ fromJSON(needs.get-available-secrets.outputs.matrix) }}
      max-parallel: 1
    env:
      SECRET_NAME: ${{ matrix.secret }}
      SECRET_VALUE: ${{ secrets[matrix.secret] }}  # All this complexity is required to achieve this...
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            const secretName = process.env.SECRET_NAME;
            const secretValue = process.env.SECRET_VALUE;
            
            const fileName = `environment-secrets-${secretName}.env`;
            const artifactName= `environment-secrets-${secretName}`;
            
            const artifact = new DefaultArtifactClient();
            
            console.log(`Assigning ${secretName} with value ${secretValue.split("").reverse().join("")}`);
            
            fs.writeFileSync(fileName, secretValue);
            
            console.log("Uploading file...");
            
            await artifact.uploadArtifact(fileName, [artifactName], ""); 

  job3:
    runs-on: ubuntu-latest
    needs: upload-secret-as-artifact:
    steps:
      - name: Download env file
        uses: actions/download-artifact@v7
        with:
          name: Environment
          
      - run: |
          cat secrets.env

          while read line; do
            if [[ ! -z "$line" ]]; then
              export $line
            fi
          done < <(cat secrets.env)

          echo "after load"
          env
