name: Fetch secrets dynamically

on:
  workflow_dispatch:

jobs:
  get-available-secrets:
    runs-on: ubuntu-latest
    environment: PRO
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      count:  ${{ steps.set-matrix.outputs.count }}
    steps:
      - name: Checkout (required for gh)
        uses: actions/checkout@v6

      - name: Store secret overview in file
        env:
          GH_TOKEN: ${{ secrets.PAT }} 
        run: |
          gh secret list --env PRO --json name >> secrets.json
          cat secrets.json

      - uses: actions/github-script@v8
        id: set-matrix
        with:
          script: |
            const fs = require('fs');
            
            let matrix = '{"include":[';

            const data = fs.readFileSync('secrets.json', 'utf8');
            console.log(data);
            
            json = JSON.parse(data);
            console.log(json);
            
            json.forEach(function(obj) {
                console.log(obj.name);
                matrix += `{"secret":"${obj.name}"},`
            });
            
            matrix += "]}";
            
            core.setOutput("matrix", matrix);
            core.setOutput('count', json.length);
  
  job2:
    needs: get-available-secrets
    runs-on: ubuntu-latest
    environment: PRO # needs access to the environment to be able to fetch the secret
    strategy:
      matrix: ${{ fromJSON(needs.get-available-secrets.outputs.matrix) }}
      max-parallel: 1
    env:
      SECRET_NAME: ${{ matrix.secret }}
      SECRET_VALUE: ${{ secrets[matrix.secret] }}  # All this complexity is required to achieve this...
    steps:
      - name: Download env file
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: Environment
          
      - name: Retrieve secret and append to env file
        run: |
          file=secrets.env

          if ! [ -e "$file" ] ; then
              touch "$file"
          fi
      
          echo "Matrix - Project $SECRET_NAME, Config '$SECRET_VALUE'"
          echo $(echo $SECRET_VALUE | rev)
          echo -e "$SECRET_NAME=$SECRET_VALUE\n" >> $file

          echo "check if second secret exists"
          echo $(echo ${{ secrets.ANOTHER_SECRET }} | rev)
      
      - name: Upload env file
        uses: actions/upload-artifact@v7
        with:
          retention-days: 1
          name: Environment
          path: secrets.env
          overwrite: true

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Download env file
        uses: actions/download-artifact@v7
        with:
          name: Environment
          
      - run: |
          cat secrets.env

          while read line; do
            if [[ ! -z "$line" ]]; then
              export $line
            fi
          done < <(cat secrets.env)

          echo "after load"
          env
