name: Fetch secrets dynamically

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
      

jobs:
  get-available-secrets:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      count:  ${{ steps.set-matrix.outputs.count }}
    steps:
      - name: Checkout (required for gh)
        uses: actions/checkout@v6

      - name: Store secret overview in file
        env:
          GH_TOKEN: ${{ secrets.PAT }} 
        run: |
          gh secret list --env PRO --json name >> secrets.json
          cat secrets.json

      - uses: actions/github-script@v8
        id: set-matrix
        with:
          script: |
            const fs = require('fs');
            
            let matrix = '{"include":[';

            const data = fs.readFileSync('secrets.json', 'utf8');
            console.log(data);
            
            json = JSON.parse(data);
            console.log(json);
            
            json.forEach(function(obj) {
                console.log(obj.name);
                matrix += `{"secret":"${obj.name}"},`
            });
            
            matrix += "]}";

            console.log(matrix);
            console.log(json.length);
            
            core.setOutput("matrix", matrix);
            core.setOutput('count', json.length);
  
  upload-secret-as-artifact:
    needs: get-available-secrets
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} # needs access to the environment to be able to fetch the secret
    strategy:
      matrix: ${{ fromJSON(needs.get-available-secrets.outputs.matrix) }}
      max-parallel: 1
    env:
      SECRET_NAME: ${{ matrix.secret }}
      SECRET_VALUE: ${{ secrets[matrix.secret] }}  # All this complexity is required to achieve this...
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            
            const secretName = process.env.SECRET_NAME;
            const secretValue = process.env.SECRET_VALUE;
            
            const fileName = `environment-secrets-${secretName}.scrt`;
            
            console.log(`Assigning ${secretName} with value ${secretValue.split("").reverse().join("")}`);
            
            fs.writeFileSync(fileName, secretValue);
      
      - name: Upload secret artifact
        uses: actions/upload-artifact@v7
        with:
          retention-days: 1
          name: environment-secrets-${{ env.SECRET_NAME }}
          path: environment-secrets-${{ env.SECRET_NAME }}.scrt
          overwrite: true

  do-something-with-secret:
    runs-on: ubuntu-latest
    needs: upload-secret-as-artifact
    steps:
      - name: Download secret files
        uses: actions/download-artifact@v7
        with:
          path: secrets/
          
      - uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const path = require("path");

            const filePath = "secrets";
            const secretLocations = fs.readdirSync("secrets", { recursive: true });
            
            console.log(secretLocations);
            
            secretLocations.forEach(location => {
                const actualLocation = filePath + "/" + location;
                if (fs.statSync(actualLocation).isFile()) {
                    const fileContent = fs.readFileSync(actualLocation, "utf8");
                    console.log(fileContent);
            
                    const fileName = path.basename(actualLocation, ".scrt")
                    console.log(fileName);
                    const envVarName = fileName.split("-").reverse()[0];
                    console.log(envVarName);
            
                    core.exportVariable(envVarName, fileName);
            
                } else {
                    console.log(`${location} is a directory`);
                }
            });

            // remove all evidence
            await io.rmRF(filePath);
            // TODO: remove artifacts

      - name: actual code
        run: echo $MYSECRET
