name: Fetch secrets dynamically V2

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true

jobs:
  get-available-secrets:
    runs-on: ubuntu-latest
    name: List available secrets for ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    outputs:
      matrix: ${{ steps.generate-matrix-input.outputs.matrix }}
      count:  ${{ steps.generate-matrix-input.outputs.count }}
    steps:
      - name: Checkout (required for gh)
        uses: actions/checkout@v6

      - name: Generate overview of secrets
        id: generate-matrix-input
        uses: ./list-secrets
        with:
          environment: ${{ inputs.environment }}
          gh-token: ${{ secrets.PAT }}


  # This intermidiate job is needed to actually fetch the secret
  # Since you can't do something like this ${{ secrets[$secret_name] }} in bash script
  # So you need to make the name of the secret available within the GitHub Expressions syntax
  upload-secret-as-artifact:
    needs: get-available-secrets
    if: ${{ needs.get-available-secrets.outputs.count > 0 }}
    name: Make ${{ matrix.secret }} secret available for ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} # needs access to the environment to be able to fetch the secret
    strategy:
      matrix: ${{ fromJSON(needs.get-available-secrets.outputs.matrix) }}
    steps:
      - name: Checkout (required for run sub-action)
        uses: actions/checkout@v6
        
      - name: Upload secret artifacts
        id: upload-secret-artifacts
        uses: ./fetch-secrets
        with:
          secret-name: ${{ matrix.secret }}
          secret-value: ${{ secrets[matrix.secret] }}  # All this complexity is required to achieve this...


  # This job represents the job which will actually use the secrets
  # The action will make the secret available as environment variable
  do-something-with-secret:
    runs-on: ubuntu-latest
    name: Do something with the actual secrest on ${{ inputs.environment }}
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    needs: [upload-secret-as-artifact, get-available-secrets]
    
    steps:
      - name: Checkout (required for run sub-action)
        uses: actions/checkout@v6
        
      - name: Provide secrets as environment variables
        id: upload-secret-artifacts
        uses: ./provide-secret
        with:
          provide-secrets: ${{ needs.get-available-secrets.outputs.count > 0 }}

      # Do something with the secrets
      - name: actual code
        run: echo $MYSECRET
