name: List secrets

on:
  workflow_dispatch:

jobs:
  #use-dynamic-secret:
  #  runs-on: ubuntu-latest
  #  environment: PRO
  #  steps:
  #    - name: Checkout (required for gh)
  #      uses: actions/checkout@v6
        
  #    - name: get secrets overview
  #      env:
  #        GH_TOKEN: ${{ secrets.PAT }} 
  #      run: |
  #        gh secret list --env PRO --json name >> secrets.json
  #        cat secrets.json
  #        jq -c '.[]' secrets.json | while read i; do
  #            val=$(jq -r '.name' <<< "$i")
  #            echo "Name: $val"
  #            value=${{ secrets[val] }}
  #            echo "Value=$value"
  #        done

  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"secret\":\"MYSECRET\"},{\"secret\":\"OTHERSECRET\"}]}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: echo "Matrix - Project ${{ matrix.secret }}, Config '${{ secrets[matrix.secret] }}'"
