name: List secrets

on:
  workflow_dispatch:

jobs:
  use-dynamic-secret:
    runs-on: ubuntu-latest
    environment: PRO
    steps:
      - name: Checkout (required for gh)
        uses: actions/checkout@v6
        
      - name: list secrets
        env:
          GH_TOKEN: ${{ secrets.PAT }} 
        run: |
          gh secret list --env PRO --json name >> secrets.json
          cat secrets.json
          jq -c '.[]' secrets.json | while read i; do
              val=$(jq -r '.name' <<< "$i")
              echo "Value: $val"
          done
