name: Central workflow which uses the secret
on:
  workflow_call:
    inputs:
      additionals:
        description: "list of additionals"
        type: string
        required: true

jobs:
  some-job:
    environment: PRO
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.additionals }}" | base64 --decode
