name: Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
      key:
        type: string
        description: Key of the secret
        required: true
      secret:
        type: string
        description: Secret value
        required: true

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mask secret
        id: mask-secrets
        run: |
          PASSWORD=$(jq -r '.inputs.secret' $GITHUB_EVENT_PATH)
          INPUT_KEY=$(jq -r '.inputs.key' $GITHUB_EVENT_PATH)
          echo ::add-mask::$PASSWORD
          echo "SECRET=$PASSWORD" >> "$GITHUB_OUTPUT"
          echo "KEY=$INPUT_KEY" >> "$GITHUB_OUTPUT"

      - name: Try to display
        env:
          SECRET: ${{ steps.mask-secrets.outputs.SECRET }}
          KEY: ${{ steps.mask-secrets.outputs.KEY }}
        run: |
          echo "Key: $KEY"
          echo ${{ github.event.inputs.key }}
          echo "$SECRET" | rev

      - name: Check if new secret should be created
        env: 
            super_secret: ${{ secrets[github.event.inputs.key] }}
        if: ${{ env.super_secret == '' }}
        run: echo "Secret does not exist; creating new secret with key ${{ github.event.inputs.key }}"

      - name: Check if new secret should be updated
        env: 
            super_secret: ${{ secrets[github.event.inputs.key] }}
        if: ${{ env.super_secret != '' }}
        run: echo "::warning::Secret already exists; updating secret with key ${{ github.event.inputs.key }}"

      - name: Checkout (required for gh)
        uses: actions/checkout@v6
          
      - name: set as password
        env:
          SECRET: ${{ steps.mask-secrets.outputs.SECRET }}
          KEY: ${{ steps.mask-secrets.outputs.KEY }}
          GH_TOKEN: ${{ secrets.PAT }}  # PAT with access to secrets only
        run: gh secret set "$KEY" --body "$SECRET" --env PRO
