name: Secrets

on:
  workflow_dispatch:
    inputs:
      password:
        type: string
        description: Secret value
        required: true

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Mask Password
        run: |
          PASSWORD=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
          echo ::add-mask::$PASSWORD
          echo PASSWORD=$PASSWORD >> $GITHUB_ENV

      - name: Try to display
        run: echo" ${{ env.PASSWORD }}"
