name: Secrets

on:
  workflow_dispatch:
    inputs:
      password:
        type: string
        description: Secret value
        required: true

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mask Password
        id: mask-secrets
        run: |
          PASSWORD=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
          echo ::add-mask::$PASSWORD
          echo "SECRET=$PASSWORD" >> "$GITHUB_OUTPUT"

      - name: Try to display
        env:
          SECRET: ${{ steps.mask-secrets.outputs.SECRET }}
        run: echo "$SECRET" | rev

      - name: Checkout (required for gh)
        uses: actions/checkout@v6
          
      - name: set as password
        env:
          SECRET: ${{ steps.mask-secrets.outputs.SECRET }}
          GH_TOKEN: ${{ github.token }}
        run: gh secret set MYSECRET --body "$SECRET"
